# Generated by Django 3.2.9 on 2021-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='carouselproduct',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
